# Generated by Django 4.1.5 on 2023-01-08 22:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=250, verbose_name='Category')),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='Url Category')),
                ('imgcat', models.ImageField(blank=True, upload_to='imgcategory/%Y/%m/%d/', verbose_name='Photo Category')),
            ],
        ),
        migrations.CreateModel(
            name='LevelofDifficulty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50, verbose_name='Level of difficulty')),
                ('slug', models.SlugField(unique=True, verbose_name='Url Level of difficulty')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50, verbose_name='Tag')),
                ('slug', models.SlugField(unique=True, verbose_name='Url Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Url Product')),
                ('shortcontent', models.TextField(verbose_name='Brief product description')),
                ('content', models.TextField(verbose_name='Full product description')),
                ('hour', models.PositiveSmallIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(23)], verbose_name='hour')),
                ('minutes', models.PositiveSmallIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(59)], verbose_name='minutes')),
                ('price', models.DecimalField(decimal_places=3, max_digits=19, null=True, verbose_name='Price')),
                ('photo_preview', models.ImageField(blank=True, upload_to='photo_preview/%Y/%m/%d/', verbose_name='Photo preview')),
                ('is_published', models.BooleanField(default=True, verbose_name='Published/Unpublished')),
                ('date_posted', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product', to='market.category', verbose_name='Product category')),
                ('levelofdifficulty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product', to='market.levelofdifficulty', verbose_name='Level of Difficulty')),
                ('tags', models.ManyToManyField(blank=True, related_name='product', to='market.tag')),
            ],
        ),
    ]
